language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
on:
  branch: master

after_success:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL

deploy:
  provider: s3
  access_key_id: $STAGING_AWS_ACCESS_KEY_ID
  secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
  bucket: $STAGING_AWS_S3_BUCKET
  skip_cleanup: true
  region: eu-west-3
  on:
    branch: develop