language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
on:
  branch: master

after_success:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL

deploy:
  provider: gcs
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET
  #region: eu-west-3
  acl: public_read
  local_dir: build
  skip_cleanup: true
  on:
    branch: develop